version: '3'

services:
    db:
        image: postgres:12-alpine
        container_name: posthog_lite_db
        environment:
            POSTGRES_USER: posthog
            POSTGRES_DB: posthog_lite
            POSTGRES_PASSWORD: posthog
        ports:
            - '5432:5432'
    redis:
        image: 'redis:5-alpine'
        container_name: posthog_lite_redis
        ports:
            - '6379:6379'
